server:
  port: 8080 #服务注册中心端口号
spring:
  application:
  name: springboot-eureka

eureka:
  instance:
    hostname: localhost #服务注册中心实例的主机名
    prefer-ip-address: true
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/
    healthcheck:
      enabled: false
ribbon:
  eureka:
    enabled: false
