server:
  port: 9090
spring:
  application:
  name: springboot-eureka-provider
eureka:
  client:
    instance:
      appname: springboot-eureka-provider
    serviceUrl:
      defaultZone: http://10.6.20.45:8080/eureka/